### ISSUE TITLE
Module Installing Error

### ISSUE THREAD

**Issue by bhavika-g** [pnlbwh/nifti-snapshot#2]
Hi, 

I am unable to install this module.

 I tried 'pip install git+https://github.com/pnlbwh/nifti-snapshot.git', but that won't work due to the absence of a setup.py file. 

I tried the other solution as given in a different issue to 'echo "export PYTHONPATH=${PYTHONPATH}:/Users/<path>/pnl_randomise/nifti-snapshot/nifti_snapshot" >> ~/.bashrc' but I still get the module not found error. 

How can I fix this?

Thanks!

**Comment by kcho** [comment]
Hi @bhavika-g 

Please follow the lines below and see if it works.

```
# Set yourself a root. This could be any directory where you have a write access.
cd <download_root>
git clone https://github.com/pnlbwh/nifti-snapshot
cd <download_root>/nifti-snapshot
pip install -r requirements.txt

# path settings
export PYTHONPATH=${PYTHONPATH}:<download_root>/nifti-snapshot
export PATH=${PATH}:<download_root>/scripts

# try running nifti_snapshot
nifti_snapshot -h
```

If it prints help message, save the `# path settings` to your ~/.bashrc.

**Comment by hbaagil** [comment]
Hi Kevin, I am having the same issue. After installation following the README.md file, nothing happens when I run randomise_summary.py. I have just tried to follow the lines above to export to PATH but it doesn't seem to be working either. When I do nifti_snapshot -h, it says command not found.

Thank you for your help in advance!
Hamzah

**Comment by kcho** [comment]
https://github.com/pnlbwh/nifti-snapshot/issues/3#issuecomment-1005989590
